# Defining Configs In YAML Format:
#MongoDB Configuration Parameters:
spring:
  application:
    name: Journal Web Application
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      #it will automatically create indexes in document fields:
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  #Setting Oauth Config:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AUTH_CLIENT_ID}
            client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
  main:
    allow-circular-references: true
  #Configuration For Creating JavaMail Bean:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL}
    password: ${JAVA_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          #For Encryption Purposes (TLS Methods) (Start Transport Layer Security):
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.abhijournalwebapp.journalWebApplication.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='44DYWLMXMG5GJE44' password='zpFR0FFTrRApShdBQbeHCH0kkdkfFtgs9/jf20/fp6iZayauWOwY1vC6YH15mR2X';
      session:
        timeout:
          ms: 45000


weather:
  api:
    key: ${WEATHER_API_KEY}

quotes-api-key: ${QUOTES_API_KEY}

server:
  port: ${SERVER_PORT_PROD}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true




#Enabling DEBUG and TRACE levels in LogBack:
#logging:
#  level:
#    com:
#      example:
#        abhijournalwebapp:
#          journalWebApplication: DEBUG
